---
minikube: 
  version: 
  enable_ingress: # < bool > Enable addon ingress 

kubectl:
  version:   

helm_vars: 
  chartname:      # Chart name  
  repo:           # Chart repo
  namespace:      # Namespace
  env: 
    SUPERUSER:    # Site superuser
    SUPERUSERPWD: # Site superuser password
    FLUSHDATA:   
  db:             # DB settings for application connection 
    name: 
    user: 
    password: 
    host: 
    port:   
    flush: # < bool > Flush all data in database when apply helm 
  web:
    host: # URL to aplication 

# Needed packages
packages: 
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common
    - socat 
    - unzip 
    - curl 
    - htop 
    - ncdu 
    - iftop 
    - atop   

# docker settings 
docker: 
  version: '18.06.3~ce~3-0~ubuntu'
  apt:
    key_id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    repository: >
               deb [arch=amd64]
               https://download.docker.com/linux/{{ ansible_distribution | lower }}
               {{ ansible_distribution_release }} stable  

