---
- name: Create dir for binaries
  file:
   path: /app/
   state: directory

- name: Install helm
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz
    dest: /app/
    mode: 0755
    creates: /app/linux-amd64/helm
    force: yes
    remote_src: yes
  register: stat_helm_status  

- debug: 
    var: stat_helm_status

- name: Copy helm 
  copy:
    src: /app/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    mode: +x    
  when: not stat_helm_status.failed

- name: Configure Helm and kindly wait for tiller pod
  shell: | 
     helm init 
     sleep 15   
     helm plugin install --version master https://github.com/sagansystems/helm-github.git
  failed_when: false   
  changed_when: false

- name: Generate values.yaml
  template:
    src: values.yml.j2
    dest: /app/values.yml 
  when: not stat_helm_status.failed

- name: Apply django-todo chart
  shell: "helm github upgrade {{ helm_vars.chartname }} --install  -f /app/values.yml  --namespace {{ helm_vars.namespace }}  --repo {{ helm_vars.repo }}"
  failed_when: false
  changed_when: false
  register: chart_apply_result
  when: not stat_helm_status.failed

- name: Info message 
  debug:
      msg:
        - '#####################################################################################################'
        - '#                                                                                                      '
        - '#   App will be availabe soon! Give some time to download images and start up services!  Approx ~30sec '
        - '#                                                                                                      '
        - "#   Application is available here: http://{{ helm_vars.web.host}}                        "
        - '#                                                                                                      '  
        - '#   If you run localy add dns record on you PC                                                         '
        - '#                                                                                                      '
        - '#  Note: Minikube configs saved in root home folder. Use them to manage minikube                       ' 
        - '######################################################################################################'