---
- hosts: all
  become: yes 
  gather_facts: no
  pre_tasks: 
    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    
  tasks: 
    - name: Collect facts
      setup:
        gather_subset:
          - '!all'
          - '!any'
          - facter

  post_tasks:
    - name: Apply minikube role
      include_role: 
        name: minikube